# Generated by Django 5.0.7 on 2024-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='age',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='height',
            field=models.FloatField(default=5.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='weight',
            field=models.FloatField(default=150.0),
            preserve_default=False,
        ),
    ]
