# Generated by Django 5.0.7 on 2024-07-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_reading_age_reading_height_reading_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='age',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='height',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='weight',
        ),
        migrations.AddField(
            model_name='reading',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
