# Generated by Django 5.0.7 on 2024-07-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_reading_age_remove_reading_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='country_avg_diastolic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='country_avg_systolic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='global_avg_diastolic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='global_avg_systolic',
            field=models.FloatField(default=0),
        ),
    ]
